CREATE TABLE Login(userName VARCHAR(10) PRIMARY KEY,
password VARCHAR(16) NOT NULL); 

CREATE TABLE User(userID INT PRIMARY KEY,
firstName VARCHAR(20) NOT NULL,
lastName VARCHAR(20) NOT NULL,
type VARCHAR(20),
userName VARCHAR(10), 
FOREIGN KEY (userName) REFERENCES Login (userName));

CREATE TABLE FoodLog(logID INT PRIMARY KEY,
date DATETIME NOT NULL,
title VARCHAR(20) NOT NULL,
userID INT, 
FOREIGN KEY (userID) REFERENCES User (userID));

CREATE TABLE FoodItems(foodName VARCHAR(20) PRIMARY KEY,
calories INT NOT NULL,
logID INT, 
FOREIGN KEY (logID) REFERENCES FoodLog (logID));

CREATE TABLE PointsEarned(value INT NOT NULL,
userID INT, 
FOREIGN KEY (userID) REFERENCES User (userID));

CREATE TABLE Comments(text VARCHAR(100),
logID INT, 
FOREIGN KEY (logID) REFERENCES FoodLog (logID));
